### ISSUE TITLE
Package Manager Recent tab shows no pictures

### ISSUE THREAD

**Issue by Gizz-G** [yolanother/ProjectAssetManager#1]
Only the empty grid is visible. Same on Win10 and Mac BigSur11.4 with Unity 2021.1.14f1

**Comment by yolanother** [comment]
![image](https://user-images.githubusercontent.com/645359/132878797-d21b53ec-7708-486d-b4d3-cb56ae24a138.png)

**Comment by yolanother** [comment]
I found the bug and the fix will go out in the next release.
